
Get http://localhost:4000

###

POST http://localhost:4000/gettoken
Authorization: Bearer eyJhbGciOiJIUzM4NCIsInR5cCI6IkpXVCJ9.eyJ2YWx1ZSI6eyJ1c2VybmFtZSI6ImJhcmFjayBvYmFtYSIsInBhc3N3b3JkIjoiMi1lbGVjdG9yYWwgb2xkIHByZXNpZGVudCBvZiB1c2EifSwiaWF0IjoxNjc3MTgwMzk5LCJpc3MiOiJiYXJhY2sgb2JhbWEiLCJzdWIiOiJwZXJzb25hbCB0b2tlbiJ9.6Z8XjA2Cfv3Yezr_jzD66ENybv5DUwIVHhT5H2yXAFs1NdEudcNI3HIhVtvaSC9V

###

POST http://localhost:4000/register/12
Content-Type: application/json

{    
  "Firstname": "romeus",
  "Lastname": "clarens",
  "Email": "romeusclarens10@gmail.com",
  "Password": "clarens(+-1998)",
  "ConfirmPassword": "clarens(+-1998)"
}

###
POST  http://localhost:4000/login/student
Content-Type: application/json

{
  "username": "prophete allrich",
  "password": "Clarens(+-1998)"
}

###
POST  http://localhost:4000/sendmail
Content-Type: application/json

{
  "DESTINATION": "romeusclarens10@gmail.com",
  "SUBJECT": "sending email confirmation",
  "HTMLBODY": "<a hre=http://localhost:4000>login<a>",
  "MESSAGE": "HELLO TECH ADMIN GREET YOU"
}

###
GET http://localhost:4000/sendphone
